name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ${{ matrix.os }}
  defaults:
   run:
    working-directory: ./IntelicaSecurityWeb/

  strategy:
   matrix:
    os: [ubuntu-latest]
    node-version: ["18.x"]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Setup and Install
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version}}
      cache: "npm"
      cache-dependency-path: "./IntelicaSecurityWeb/package-lock.json"

   - name: Clean Cache
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm cache clean --force

   - name: Install dependencies
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm install -f

   - name: Build
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm run build

 create-docker-image:
  runs-on: ubuntu-latest
  steps:
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v3

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_USERPASSWORD }}

   - name: Build and push
     uses: docker/build-push-action@v6
     with:
      push: true
      tags: MaxsPCF/security-web:latest
