name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ${{ matrix.os }}
  defaults:
   run:
    working-directory: ./IntelicaSecurityWeb/

  strategy:
   matrix:
    os: [ubuntu-latest]
    node-version: ["18.x"]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Setup and Install
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version}}
      cache: "npm"
      cache-dependency-path: "./IntelicaSecurityWeb/package-lock.json"

   - name: Clean Cache
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm cache clean --force

   #  - name: Accede carpeta proyecto
   #    run: cd ./IntelicaSecurityWeb

   - name: Install dependencies
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm install -f

   - name: Build
     working-directory: ./IntelicaSecurityWeb
     run: |
      npm run build
