name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

#  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#  contents: write
#  pages: write
#  id-token: write

jobs:
 build:
  name: Build and Test
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [20.x]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version }}
      cache: "npm"
      cache-dependency-path: package-lock.json

   - name: Install dependencies
     working-directory: .
     run: npm install

   - name: Build
     working-directory: .
     run: npm run build
#    - name: Test
#      run: npm run test:ci
#    - name: Archive build
#      if: success()
#      uses: actions/upload-artifact@v1
#      with:
#       name: deploy_dist
#       path: dist

#    - name: Archive code coverage result
#      if: success()
#      uses: actions/upload-artifact@v1
#      with:
#       name: deploy_coverage
#       path: coverage
#  deploy:
#   runs-on: ubuntu-latest
#   needs: build
#   steps:
#    - name: Checkout
#      uses: actions/checkout@v1
#    - name: Download build
#      uses: actions/download-artifact@v1
#      with:
#       name: deploy_dist
#    - name: Deploy to GitHub Pages
#      uses: JamesIves/github-pages-deploy-action@releases/v3
#      with:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       BRANCH: gh-pages
#       FOLDER: deploy_dist/angular-demo
