name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ubuntu-latest ${{ matrix.os }}

  strategy:
   matrix:
    os: [ubuntu-latest]
    node-version: [18.19.1]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Setup and Install
      # You may pin to the exact commit or the version.
      # uses: zirkelc/setup-and-install@e3adcf875c60174b04e738c1b11dcabdd5adc893
     uses: zirkelc/setup-and-install@v1
     with:
        # Node.js version for setup-node
      node-version: 22.1.0

   #- name: Setup Node.js ("${{ matrix.node-version}}" Version)
   #  uses: actions/setup-node@v4
    # with:
    #  node-version: ${{ matrix.node-version}}, # <-- use "latest" for the most recent Node.js version

   - name: Install dependencies
     run: cd ./Intelica.Security.Web

   - name: Install dependencies
     run: npm install -f

   - name: Build
     run: npm run build
