name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ${{ matrix.os }}

  strategy:
   matrix:
    os: [ubuntu-latest]
    node-version: [20]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Setup and Install
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version}}
      cache: "npm"

   - name: Accede carpeta proyecto
     run: cd ./IntelicaSecurityWeb

   - name: Clean global cache
     run: npm cache clean --force

   - name: Install dependencies
     run: npm install -f

   - name: Build
     run: npm run build
