name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ${{ matrix.os }}

  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest, macos-latest]
    node-version: [18, 20, 22]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v4

   - name: Clean global cache
     run: npm cache clean --force

   - name: Setup Node.js ${{ matrix.node-version }}
     uses: ./
     with:
      node-version: ${{ matrix.node-version }}
      cache: "npm"

   - name: Install dependencies
     run: npm install

   - name: Build
     run: npm run build
