name: workflow Angular

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]

jobs:
 build:
  name: Build (${{ matrix.node-version}}, ${{ matrix.os }})
  runs-on: ${{ matrix.os }}

  strategy:
   matrix:
    os: [ubuntu-latest]
    node-version: [18]

  steps:
   - name: Checkout the source code
     uses: actions/checkout@v3

   - name: Setup and Install
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node-version}}
      cache: "npm"
      cache-dependency-path: ${{github.workspace}}/IntelicaSecurityWeb/package-lock.json

   - name: Accede carpeta proyecto
     run: cd ./IntelicaSecurityWeb

   - name: Install dependencies
     run: npm install -f

   - name: Build
     run: npm run build
